### ISSUE TITLE
"TypeError: Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by twomice** [progressivetech/net.ourpowerbase.remoteform#19]
Hi,

Setup:
1. CiviCRM is running the latest master code for this extension, under WordPress
2. An external site running Drupal will host the public-facing profile form.

After setting up per instructions, I copy the javascript code to a page on my external Drupal site. The form displays displays the warning, "Sorry, we encountered an error! See console log for more details.", and the console log reports only this:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at remoteform.js:1241
    at XMLHttpRequest.request.onreadystatechange (remoteform.js:687)
```

However, the remote form otherwise appears to display well, and submitting it actually creates the data in my WordPress/CiviCRM site.

Considering that it works, is this `TypeError` something that can be ignored? If so, how could we remove the "Sorry..." warning on the page?  Or, if not, how can I help to debug and address this error?

**Comment by jmcclelland** [comment]
Thanks for posting. Line 1241 is the part of the javascript where it tries to build a drop down list for state province and for countries. Do you have a state or country field in your profile? I wonder if the CiviCRM install is configured without any "Available countries" or "Available states" under Administer -> Localization -> Language, Currency, and Location.

That might be the way to make the error go away. 

It would be nice to not throw such an error if countries or states are not defined, but let me know if that is the problem first.

**Comment by twomice** [comment]
Hi Jamie. You were close. There were available countries and states configured, but there was no default country configured; perhaps this causes remoteform to try and pull states for a null country, leading to the error. By defining the "default country" setting, the error goes away. Thanks!
