### ISSUE TITLE
cfg.SuccesMsg parameter doesn't work.

### ISSUE THREAD

**Issue by eth4ever** [progressivetech/net.ourpowerbase.remoteform#2]
It looks like a great extension.
I managed to change some cfg parameters. Only the cfg.SuccesMsg didn't change.

cfg.initTxt, cfg.submitTxt, cfg.cancelTxt were all fine.

Will it be possible to prefill a form with remote form, base on a personalized link in an email, using a checksum token?

**Comment by jmcclelland** [comment]
Woops, that was a documentation error. I just pushed a fix. cfg.successMsg should work (lowerbase s for success).

And, no, unfortunately, it's not possible to use a checksum to prefill a form - and it probably will not be high on the list of things to implement first. I plan to focus on events and petitions next.

**Comment by eth4ever** [comment]
It works fine now.
