### ISSUE TITLE
Error: "Response returned with non-OK status", xhr.status = 0

### ISSUE THREAD

**Issue by twomice** [progressivetech/net.ourpowerbase.remoteform#20]
I suspect I'm doing something wrong, but can't see what that is. (Could it be that one site is on a subdomain of the other site's domain?)

For two sites civi.redacted.com (civicrm with remoteform installed) and redacted.com (another site running drupal 7 (and indeed, the civi site is running on a subdomain of the just-drupal site):

On civi.redacted.com:
* Remoteform is installed (latest master as of today).
* At /civicrm/admin/remoteform, the "Allow forms to be submitted from the following locations." says "http://redacted.com"
* A profile is create with just contact fields first name, last name, and primary email; set for stand-alone form usage, such that it has a public url at https://civi.redacted.com/civicrm/profile/create?gid=16&reset=1
* On this profile, the "remote form" setting is enabled. I copy the JS code presented there.
* I then ensure I'm logged out from civi.redacted.com

On redacted.com:
* I create a drupal node containing the JS code copied above.
* I view the node, and see the error "Sorry, we encountered an error! See console log for more details".
* Console log says this:

```
Error: "Response returned with non-OK status"
    onreadystatechange https://civi.redacted.com/sites/default/files/civicrm/ext/net.ourpowerbase.remoteform/remoteform.js:693
remoteform.js:372:13
https://civi.redacted.com/civicrm/remoteform remoteform.js:694:19
Object { action: "getfields", entity: "Profile", params: {…} }
remoteform.js:695:19
XMLHttpRequest
​
mozAnon: false
​
mozSystem: false
​
onabort: null
​
onerror: null
​
onload: null
​
onloadend: null
​
onloadstart: null
​
onprogress: null
​
onreadystatechange: function onreadystatechange()
​
ontimeout: null
​
readyState: 4
​
response: ""
​
responseText: ""
​
responseType: ""
​
responseURL: ""
​
responseXML: null
​
status: 0
​
statusText: ""
​
timeout: 0
​
upload: XMLHttpRequestUpload { onloadstart: null, onprogress: null, onabort: null, … }
​
withCredentials: false
```

I also tried this command
```
curl -H "Origin: https://redacted.com" -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: X-Requested-With" -X OPTIONS --verbose https://civi.redacted.com/civicrm/remoteform 2>&1 | grep Allow-Origin
```
It returned no output.

Any clues on what I've missed, or tips on debugging?

**Comment by twomice** [comment]
Note to self: when this is resolved, follow up on https://lab.civicrm.org/extensions/activityprofile/issues/1#note_32036

**Comment by mlutfy** [comment]
Is it Drupal7 or 8? (see #22)

**Comment by twomice** [comment]
D7. OP updated.

**Comment by jmcclelland** [comment]
Anything in ConfigAndLog? Also, in the console, there should be an option to show what the server response was - which I suspect would have an error message generated by CiviCRM and would be key to debugging.

**Comment by twomice** [comment]
Sorry to say, this was so long ago that the client has moved us on to solving other issues, and remoteform turned out not to be needed in this case (not primarily because of this issue, rather for their own workflow reasons). Thus, I'm not able to provide much additional information. Please feel free to close this issue.

**Comment by jmcclelland** [comment]
Thanks for reporting back.
