### ISSUE TITLE
Support for Mailing Subscribe page?

### ISSUE THREAD

**Issue by JoeMurray** [progressivetech/net.ourpowerbase.remoteform#24]
I'm pretty sure this is a feature request, but just wanted to ask if this extension currently supports Mailing Subscribe page ie https://docs.civicrm.org/user/en/latest/email/set-up/#using-the-subscribe-link? We're likely okay just using a profile page to create subscriptions.

**Comment by jmcclelland** [comment]
Hi Joe - Interesting - I hadn't considered that. I would be open to a PR, but probably won't be adding any new features to remoteform myself until the new forms API is sorted out a bit more. I'm currently in a holding pattern until I figure out how to make remote form simply work with afform designed forms.

**Comment by JoeMurray** [comment]
Understood.
