### ISSUE TITLE
Source tracking per-remote-site

### ISSUE THREAD

**Issue by twomice** [progressivetech/net.ourpowerbase.remoteform#27]
We have a use case in which RemoteForms will be used to serve one CiviCRM contribution page on several different sites. We'd like to have a way to record (most likely in contribution.source) which site the contribution came from. In other words, instead of contribution.source reading "Online Contribution: My Contribution Page" it might be configured to read "From example.com, via RemoteForms" or some other arbitrary string.

I suppose this might also be done with custom fields, but either way, we'd need a way to configure the RemoteForm code to fill in a predictable value in the field, different for each remote site.

Any thoughts on how best to make that happen? Interested in a PR that might support such functionality? Any "hey now, slow down there" words of caution?

**Comment by jmcclelland** [comment]
There is a documented API for changing everything here:

https://github.com/progressivetech/net.ourpowerbase.remoteform/blob/master/docs/api.md

As is often the case, I think I exposed the wrong knobs. There is no easy way to insert a default value.

On the bright side, there is a hard way :).

You can override the `createFieldDiv` and after a few layers of abstraction create the html widget for any field that is included in the profile. So, if you can stick the source field in the profile, you could use javascript to make it hidden and also set the default value.

**Comment by twomice** [comment]
So in theory this is possible without altering the extension code. Will try that. Thanks.

**Comment by twomice** [comment]
Now that we have #35 fixed, this is pretty easy with custom JS in a separate extension. Some resources for the curious:

- Demo video showing how it works: https://youtu.be/QRRJ_-uNoA0
- Extension code providing features in the demo video: https://github.com/twomice/com.joineryhq.hnremoteform

Closing now. Thanks @jmcclelland !
