### ISSUE TITLE
can't avoid this show-stopper error: "Duplicate error - existing contribution record(s) have a matching Transaction ID or Invoice ID"

### ISSUE THREAD

**Issue by twomice** [progressivetech/net.ourpowerbase.remoteform#28]
I can't seem to avoid this error message when submitting a remote form:

`Duplicate error - existing contribution record(s) have a matching Transaction ID or Invoice ID. Contribution record ID(s) are: 95`

Steps to reproduce:

1. Install a brand new Drupal 7 site with CiviCRM (5.26.2), with Sample Data, at https://drupal.local
1. Install Remote Forms (master branch, currently at f40af09a6bbe2a8459a86fe20e6202fdf8cbd418)
1. Configure Remote Forms Settings at /civicrm/admin/remoteform to allow connections from https://static.local
1. Open the "Help Support CiviCRM" contribution page configuration at /civicrm/admin/contribute/settings?action=update&reset=1&id=1 ; check the "Allow remote submissions to this contribution page." checkbox, and copy the provided embed code (This contribution page is provided with CiviCRM's Sample Data during the civicrm installation; it uses CiviCRM's Test/Dummy Payment Processor) and no profiles.
1. Create a new static html file, visible at https://static.local/test.html; paste in the copied embed code within the `<body>` tag.
1. View https://static.local/test.html ; observe that the contribution form is displayed without error. Fill in all fields, including '4111111...' credit card number, etc. and submit the form.
1. Observe the form spins for a moment before displaying the above-mentioned error message:
![remoteforms-error](https://user-images.githubusercontent.com/759449/88955714-e68ecb80-d261-11ea-9589-9cb985fa87d1.png)
1. In Drupal/CiviCRM, search for contributions and observe no new contribution has been created.
1. Also use CiviCRM API (`cv api Contribution.get sequential=1 id=95`) and observe there is no contribution with that ID.

Since this is a clean install, I'm not sure what could be causing this. Is the Dummy Processor not supported? Do I need a profile with an email address (which in the above scenario doesn't display on the WP remoteform)? Any other ideas?

**Comment by twomice** [comment]
(Edit: modified the steps in the OP to simplify the error case by eliminating WordPress, so that the "remote" site is just static HTML.)

**Comment by lucky091588** [comment]
I have reproduced the error using both Dummy Processor and Authorize.net.

**Comment by jmcclelland** [comment]
Hi all - just a note to say I'm sorry I haven't gotten back to you on this. I've been buried trying to get all our sites upgraded in time for the security release tomorrow. Now that's done, but I still probably won't have time to really focus on this before next week. Almost all the groups we support are using Stripe - so it's likely a bug that only affects other payment processors (judging from the dummy account replication of the error). Hopefully I'll be able to dig in next week to try to help sort things out.

**Comment by twomice** [comment]
@jmcclelland I think this is a regression caused by 989a4edbae48528d03a1dac81f50c0b3d4c06a40. Removing [line 129](https://github.com/progressivetech/net.ourpowerbase.remoteform/commit/989a4edbae48528d03a1dac81f50c0b3d4c06a40#diff-95b8d58682bc2d04c1c48ba337983304R129) just makes the problem go away (makes sense when you look at [line 131](https://github.com/progressivetech/net.ourpowerbase.remoteform/commit/989a4edbae48528d03a1dac81f50c0b3d4c06a40#diff-95b8d58682bc2d04c1c48ba337983304R131).  PR forthcoming.

**Comment by jmcclelland** [comment]
Thank you! What a dumb mistake with an easy fix.
