### ISSUE TITLE
Avoid polluting global namespace in your example

### ISSUE THREAD

**Issue by tttp** [progressivetech/net.ourpowerbase.remoteform#3]
Hi,

on your example, you have config that is declared as a global variable, 

```
var config = {...}
remoteForm(config)
```
It will inevitably lead to some users messing with an existing config global variable in their site. Either (as the widget generated) 

```
remoteForm({...})

or

(function(config){
  remoteForm(config);
})({...});
```

I've spend time designing widget API recently, one thing that was requested is to be able to specify the dom where to embed the form (I'm assuming you are adding it where the js is currently?)

Last but not the least: so you are able to boostrapify profiles? It would be useful as well locally on the site of civi too, so we can use profiles and keep some sane styling. Would it be possible?

**Comment by jmcclelland** [comment]
Thanks for the excellent feedback. I just fixed the global config variable problem.

As for specifying where to embed the form - you can pass parentElementId via the config object to change that (see the [api docs](https://github.com/progressivetech/net.ourpowerbase.remoteform/blob/master/docs/api.md)).

And for bootstrapifying... the default css classes used to generate the html are all bootstrap classes. So, if you have already loaded bootstrap on the page, the forms generated should already be bootstrapified (you can omit the CSS file entirely).

If you don't have bootstrap loaded on your site, you can include the default CSS line and get a bootstrap-like feel.

Or, you can alter all the class options by passing in special css parameters via the config object.
