### ISSUE TITLE
Update to match current civicrm code (5.28.3 at time of writing)

### ISSUE THREAD

**Issue by twomice** [progressivetech/net.ourpowerbase.remoteform#33]
Hi @jmcclelland Looks like the CRM_Contribute_Form_Contribution_RemoteformConfirm class file needs a small edit to match the latest changes in CiviCRM (since when I'm not sure, but definitely needed for the current 5.28.3). PR forthcoming.

**Comment by mlutfy** [comment]
Nice fix!

(I think this issue can now be closed?)

**Comment by twomice** [comment]
👍
