### ISSUE TITLE
On Behalf / Honoree on Contribution page is not appearing

### ISSUE THREAD

**Issue by shaneonabike** [progressivetech/net.ourpowerbase.remoteform#55]
Hi there,

Thanks for building a great extension.

I was just curious if this was tested with the _Honoree_ and/or _On Behalf_ elements of a Contribution page. In our case, the fields associated don't seem to appear.

Thanks!

**Comment by jmcclelland** [comment]
No, unfortunately RemoteForm only works with very basic contribution pages. Given the future of oembed and CiviCRM (https://lab.civicrm.org/dev/core/-/issues/2994) it's unlikely I will be adding more features.
