### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MegaphoneJon** [progressivetech/net.ourpowerbase.remoteform#7]
Hey Jamie,

Thanks for writing this cool extension!  As you can see from my PRs, I played around with it a bit today before realizing that it needs more features than I'm willing to write (e.g. recurring payments, in honor/memory of, displaying help text from the profiles, etc.)

That said, I'm happy to push this forward and see it mature.  I was wondering if there's a roadmap?  In particular, I'm interested in whether you're considering integrating with CiviMRF.  This would allow submission through the form processor extension, for instance.

Of course, this is a nice lightweight solution for a lot of folks, so if the intent is to remain separate, that also makes sense!

**Comment by jmcclelland** [comment]
Hi Jon, 

Thanks for your pull requests! Much appreciated.

My immediate plans are:

 * Fix bugs so simple contribution pages and simple profiles work better
 * Add support for simple event registration pages
 * Add support for simple petition pages

My driving motivation is that I'm tired of creating drupal themes to mimic our groups' web pages and want to simply hand them some lines of code that run on their web site (which I don't have access to and often is neither a drupal or wordpress site - hence CiviMRF is not a good option).

After I take these short term steps, I imagine I will be seeing what kind of progress is being made with [the new formbuilder project](https://civicrm.org/make-it-happen/form-builder-a-prototype). My fantasy is that Tim and Coleman will see my remoteform code and decide they should build the same functionality and then we can retire this extension. 

Alternatively, I suspect I will focus on getting it to work with form builder.

In principle, integrating with CiviMRF is a great idea and would create the best of both worlds. However, I suspect that form builder will be a game changer and could make both remoteform and CiviMRF obsolete, so for now I'm aiming for the lower hanging fruit and then I'm going to wait and see.
