### ISSUE TITLE
All groups are exposed to the remote form

### ISSUE THREAD

**Issue by eth4ever** [progressivetech/net.ourpowerbase.remoteform#8]
When I use a  groups in a profile that is used for the remote form, it shows a nice pull down menu.
But not only the public groups are exposed. All the groups appear in the remote form. Whereas I would expect only the public groups to be exposed to the remote form.

**Comment by jmcclelland** [comment]
I'm not quite sure what to do with this one. I experimented by adding the groups field to my profile. When I use core CiviCRM links to view the form in edit mode while logged in OR while not logged in, CiviCRM didn't show me the field at all. I'm not sure what controls are in place or even what kind of logic CiviCRM has around groups in this context.

In the short term, you can always override the display of that field. remoteform is extremely customizable. Here's some example code that allows you to control exactly which groups are displayed:

```
function myCreateFieldDiv(key, def, type, createFieldFunc, wrapFieldFunc) {
  if (key == 'group_id') {
    def.options = {
      1: "Group one",
      2: "group two"
    }
  }
  var field = createFieldFunc(key, def, type);
  if (field === null) {
    return null;
  }
  return wrapFieldFunc(key, def, field);
}

var remoteFormConfig = {
 url: "https://YOURSERVER.ORG/civicrm/remoteform",
 id: 1,
 entity: "Profile",
 createFieldDivFunc: myCreateFieldDiv
};
if (typeof remoteForm !== "function") {
  document.getElementById("remoteForm").innerHTML = "Oh no! I was not able to display the form! Please check your security settings (for example Privacy Badger) and allow remote javascript to be displayed from ptp.loc.cx."
  document.getElementById("remoteForm").style.color = "red";
}
else {
  remoteForm(remoteFormConfig);
}
</script>
```

**Comment by eth4ever** [comment]
Hi Jaimie,
When a profile with groups is used in a Civi form, only the “public” groups are are visuable.

But most of the time you need more controle, which groups to be exposed on which form. 

Although I’m not a coder I’ll try your suggestions.

**Comment by eth4ever** [comment]
It work fine. Thank you.
With this code I get a pull down menu with the different groups. Is there a function to get a check box with the choosen groups?

**Comment by jmcclelland** [comment]
Great, glad that worked. And yes, you can change it to check boxes.

In this part of the code:

```
if (key == 'group_id') {
    def.options = {
      1: "Group one",
      2: "group two"
    }
  }
```

Change to:

```
if (key == 'group_id') {
    def.options = {
      1: "Group one",
      2: "group two"
    };
    type = 'checkbox';
    // Or...
    type = 'radio';
  }
```

**Comment by eth4ever** [comment]
It works great. Thank you.
And how do I make a field mandatory of set a default value for that field?

**Comment by jmcclelland** [comment]
Not tested... but I think this should work:
```
def.default_value = "red"
def["api.required"] = 1
```

Since the key "api.required" has a period in it, you have to use a different syntax to change the value.

**Comment by jmcclelland** [comment]
I think this issue is resolved.

**Comment by JoeMurray** [comment]
Superb service, @jmcclelland !

**Comment by eth4ever** [comment]
> I think this issue is resolved.

Yes. Thank you.
